# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: circleci/node:14 # Use the appropriate Node.js version
#     working_directory: ~/project

#     steps:
#       - checkout

#       # Restore cached node_modules to speed up builds
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package-lock.json" }}

#       # Install npm dependencies
#       - run:
#           name: Build the React app
#           command: npm install

#       # Save node_modules to cache to speed up future builds
#       - save_cache:
#           key: v1-dependencies-{{ checksum "package-lock.json" }}
#           paths:
#             - ./node_modules

#       - run: npm test

#       - run: npm start

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14 # Use the appropriate Node.js version

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      - run: npm build

      - run: npm deploy