version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14 # Use the appropriate Node.js version
    working_directory: ~/project

    steps:
      - checkout

      # Restore cached node_modules to speed up builds
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      # Install npm dependencies
      - run:
          name: Build the React app
          command: npm install

      # Save node_modules to cache to speed up future builds
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: npm test

      - run: npm start

workflows:
  version: 2
  build-deploy:
    jobs:
      - build